Repository kowainik/life-sync, pull requests merged in 2018-06, with the labels that each got.

#13 [#3] Cosmetics
  .travis.yml
  CHANGELOG.md
  README.md
  Setup.hs
  app/Main.hs
  app/Options.hs
  b
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Init.hs
  src/Life/Main/Update.hs
  src/Life/Shell.hs
  src/Prelude.hs
  stack-8.4.3.yaml
  stack.yaml
Labels: build

#14 [#2] Switch toml-parser to tomland
  life-sync.cabal
  src/Life/Configuration.hs
  stack-8.4.3.yaml
  stack.yaml
Labels: library

#17 [#15] Add roundtrip property test for config
  life-sync.cabal
  src/Life/Configuration.hs
  test/Spec.hs
  test/Test/Roundtrip.hs
Labels: tests

#16 [#8] Add colorful error handling
  life-sync.cabal
  src/Life/Github.hs
  src/Life/Main/Init.hs
  src/Life/Main/Update.hs
  src/Life/Message.hs
Labels: UX

#19 [#5] Add life remove command
  app/Main.hs
  app/Options.hs
  life-sync.cabal
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Remove.hs
Labels: enhancement

#18 [#4] Add list of predefined files to 'life init'
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Main/Init.hs
  test/Test/Roundtrip.hs
Labels: UX, enhancement

#23 [#21] Refactor check for .life and dotfiles
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Init.hs
  src/Life/Main/Remove.hs
  src/Life/Message.hs
  src/Life/Shell.hs
Labels: UX, enhancement

#24 [#22] Add --dir --file options
  app/Main.hs
  app/Options.hs
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Remove.hs
Labels: UX

#28 [#12] Add life push command
  app/Main.hs
  app/Options.hs
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Init.hs
  src/Life/Main/Push.hs
  src/Life/Validation.hs
Labels: UX, enhancement, git/hub

#30 [#26] Check if repository is in sync with remote
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Push.hs
  src/Life/Main/Remove.hs
  src/Life/Shell.hs
Labels: UX, git/hub

#33 [#6] Implement 'life pull' command
  app/Main.hs
  app/Options.hs
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Pull.hs
  src/Life/Main/Push.hs
  src/Life/Main/Remove.hs
  src/Life/Message.hs
Labels: UX, enhancement, git/hub

#34 [#32] Add git diff view before pushing
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Init.hs
Labels: enhancement, git/hub

#35 [#31] Show running commands
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Shell.hs
Labels: UX, enhancement, git/hub

#37 [#9] Write README
  README.md
Labels: doc
