Repository kowainik/life-sync, pull requests merged in 2020-03, with the labels that each got.

#67 [#65] Revive life-sync repo (cleanup, update, etc.)
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  app/Main.hs
  app/Options.hs
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Core.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Validation.hs
  src/Prelude.hs
  stack.yaml
  test/Test/Roundtrip.hs
Labels: refactoring

#71 [#68] Move to validation-selective
  .travis.yml
  life-sync.cabal
  src/Life/Main/Push.hs
  src/Life/Validation.hs
  stack.yaml
Labels: library

#73 [#70] Move to shellmet
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Github.hs
  src/Life/Main/Add.hs
  src/Life/Main/Init.hs
  src/Life/Main/Pull.hs
  src/Life/Main/Push.hs
  src/Life/Main/Remove.hs
  src/Life/Path.hs
Labels: library, refactoring

#76 [#75] Move to colourista
  life-sync.cabal
  src/Life/Message.hs
Labels: library, refactoring

#78 [#74] Get rid of tasty-* deps in tests
  life-sync.cabal
  stack.yaml
  test/Spec.hs
  test/Test/Configuration.hs
Labels: library, refactoring, tests

#80 [#79] Remove microlens-platform dep
  .stylish-haskell.yaml
  life-sync.cabal
  src/Life/Configuration.hs
  src/Life/Main/Add.hs
  src/Life/Main/Push.hs
  src/Life/Main/Remove.hs
Labels: library, refactoring

#81 [#77] Optimize deps: remove 'fmt'
  life-sync.cabal
  src/Life/Configuration.hs
  stack.yaml
  test/Test/Configuration.hs
Labels: library, refactoring, tests

#82 [#69] Move CLI options inside library
  app/Main.hs
  life-sync.cabal
  src/Life/Cli.hs
  src/Life/Main.hs
Labels: refactoring

#86 [#51] Introduce `newtype CommitMsg` and use it
  src/Life/Core.hs
  src/Life/Github.hs
  src/Life/Main/Push.hs
Labels: enhancement, refactoring

#88 [#84] Add meta info to library modules
  CHANGELOG.md
  LICENSE
  life-sync.cabal
  src/Life/Cli.hs
  src/Life/Configuration.hs
  src/Life/Core.hs
  src/Life/Github.hs
  src/Life/Main.hs
  src/Life/Main/Add.hs
  src/Life/Main/Init.hs
  src/Life/Main/Pull.hs
  src/Life/Main/Push.hs
  src/Life/Main/Remove.hs
  src/Life/Message.hs
  src/Life/Path.hs
Labels: doc, refactoring

#87 [#83] Add Travis binary releases
  .travis.yml
Labels: build

#89 Update CHANGELOG for 1.1.0.0 release
  CHANGELOG.md
  life-sync.cabal
Labels: doc

#90 [#40] Add homebrew formula for mac
  README.md
Labels: build, doc

#91 [#85] Add Ubuntu PPA
  README.md
Labels: doc
